### ISSUE TITLE
No errors. Just dont respond to commands sometimes and no have the slowmode.

### ISSUE THREAD

**Issue by Diegxs** [Blob-Development/command-handler#1]
> The bot is online. No have errors in the console. There is a file that is done every time the bot is powered up. Called json.sqlite and it is empty. I do not understand what is.

![image](https://user-images.githubusercontent.com/71246795/103061060-b7119000-456f-11eb-80ee-666bbe7b651c.png)
![image](https://user-images.githubusercontent.com/71246795/103062068-cba35780-4572-11eb-8779-ad299bb597ef.png)
![image](https://user-images.githubusercontent.com/71246795/103062100-d9f17380-4572-11eb-8f97-4d280c0e0e61.png)

**Comment by conver4y** [comment]
- Have you tried to fill the prefix on config.json?
• json.sqlite is the brain of your bot database, nothing to worried about.

**Comment by Diegxs** [comment]
Yes, i have a prefix in config.json, In fact, before I had a custom one but I changed it for the same problem as the default. 
![image](https://user-images.githubusercontent.com/71246795/103811484-955de180-5022-11eb-8342-098b1d3e5dc9.png)

**Comment by conver4y** [comment]
Can I see your repository/code?

**Comment by Diegxs** [comment]
Hey, thanks for the help ray, but I solved it, I don't know if it has to do, but this is solved by deleting the json.sqlite and making the necessary changes, and then letting the file automatically do. Thanks anyway!
